Feature/ATG-60 Enums (figures colors)
IraCherginyshka/AwesomeTetrisGame pull request #18
Opened 2019-11-14 10:09 UTC by IraCherginyshka

Create colors enum for figures

2019-11-14 17:29 UTC, oleksandrstarov requested changes

2019-11-14 17:29 UTC, oleksandrstarov commented on src/app/enums/figures-colors.ts
> +  'Default' = '#2b3a42',
No need to use string literals, i recommend to use DEFAULT='val'

2019-11-14 17:29 UTC, oleksandrstarov commented on src/app/enums/figures-colors.ts
> +const enum FiguresColors {
should be declared as export enum FiguresColors

2019-11-14 17:29 UTC, oleksandrstarov commented on src/app/enums/figures-colors.ts
> +const enum FiguresColors {
Please rename to figures-colors.enum.ts

2019-11-14 17:29 UTC, oleksandrstarov commented on src/app/enums/figures-colors.ts
> +export default FiguresColors;
no need to use this line

2019-11-14 17:36 UTC, IraCherginyshka commented on src/app/enums/figures-colors.ts
> +  'Default' = '#2b3a42',
Done

2019-11-14 17:40 UTC, IraCherginyshka commented on src/app/enums/figures-colors.ts
> +const enum FiguresColors {
Done

2019-11-14 17:41 UTC, IraCherginyshka commented on src/app/enums/figures-colors.ts
> +const enum FiguresColors {
Done

2019-11-14 17:41 UTC, IraCherginyshka commented on src/app/enums/figures-colors.ts
> +export default FiguresColors;
Done

2019-11-15 08:59 UTC, oleksandrstarov approved these changes

2019-11-15 13:50 UTC, oleksandrstarov approved these changes

2019-11-15 13:50 UTC, merged