Feature/ATG-63 Create canvas, class Figure, styles to board, logic game (move down)
IraCherginyshka/AwesomeTetrisGame pull request #22
Opened 2019-11-15 08:32 UTC by IraCherginyshka

Implamenting game logic.
Create class Figure
Create canvas in game-component
Move down figure

2019-11-15 14:48 UTC, oleksandrstarov requested changes

2019-11-15 14:48 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +import Block from '../../models/Block';
No such property in this branch

 ERROR in src/app/components/game-board/game-board.component.ts(3,19): error TS2307: Cannot find module '../../models/Block'.

2019-11-15 14:48 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.html
> +  <canvas #canvas width="325" height="500" class="board-canvas"></canvas>
width="325" height="500"  -- "Magic numbers"

2019-11-15 14:48 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +
please do not add en empty line between class members with same access modifier

2019-11-15 14:48 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +  makeBoardEmptyMatrix(width, height) {
please add types to parameters

2019-11-15 14:48 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +  makeBoardEmptyMatrix(width, height) {
Can be private

2019-11-15 14:48 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +  drawBoard(matrix) {
can be private

2019-11-15 14:48 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +      lineNumber--;
get no-pluplus error for es lint for this row, please disable this rule

2019-11-15 14:48 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +  makeBoardEmptyMatrix(width, height) {
add return type

2019-11-15 14:48 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +  drawBoard(matrix) {
add parameter type and return value

2019-11-15 14:48 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +          block.fillBoardBlock(indexX, indexY);
duplicate of line 44, extract out of if else statements

2019-11-15 14:48 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +        }
The only difference of this block is color parameter - can be refactored into 
`const color =  item ? 'color1' : 'color2';
new Block(this.ctx, color).fillBoardBlock(indexX, indexY);

`

2019-11-15 14:48 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +  play() {
add return type

2019-11-15 14:48 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +      if (height + figureMatrix.length === 20) {
20 is magic number

2019-11-15 14:48 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +    const { figureMatrix } = newFigure;
we only using length of figureMatrix, so i would write 

`const itemHeight = newFigure.figureMatrix.length `; 

and use itemHeight later

2019-11-15 14:48 UTC, oleksandrstarov commented on src/app/models/Figure.ts
> +  showFigure(height: number, boardMatrix: any[]) {
please add return type

2019-11-15 14:48 UTC, oleksandrstarov commented on src/app/models/Figure.ts
> +        ...this.figureMatrix[figureLine],
Please check what is returned by this line

2019-11-15 14:56 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +import Block from '../../models/Block';
I fixed it

2019-11-15 15:03 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +
EsLint
I'll delete this rule

2019-11-18 08:57 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.html
> +  <canvas #canvas width="325" height="500" class="board-canvas"></canvas>
Done

2019-11-18 10:15 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +  makeBoardEmptyMatrix(width, height) {
Done

2019-11-18 10:15 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +  play() {
Done

2019-11-18 10:16 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +  makeBoardEmptyMatrix(width, height) {
Done

2019-11-18 10:17 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +      if (height + figureMatrix.length === 20) {
Done

2019-11-18 10:21 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +    const { figureMatrix } = newFigure;
Done

2019-11-18 10:21 UTC, IraCherginyshka commented on src/app/models/Figure.ts
> +  showFigure(height: number, boardMatrix: any[]) {
Done

2019-11-18 11:15 UTC, IraCherginyshka commented on src/app/models/Figure.ts
> +        ...this.figureMatrix[figureLine],
This line returns a list of items, if I delete spread operator, I'll add array to the selected line.
Is it wrong?

2019-11-18 13:21 UTC, oleksandrstarov requested changes

2019-11-18 13:21 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +  private boardMatrix: any[];
This variable value clearly generated by makeBoardEmptyMatrix, I cant see any reason not to assign FiguresColors[][]  type to it

2019-11-18 13:21 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +  makeBoardEmptyMatrix(width: number, height: number): FiguresColors[][] {
Can be private

2019-11-18 13:21 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +  play(): void {
Can be private

2019-11-18 13:21 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +          block.fillBoardBlock(indexX, indexY);
both are same. Looks strange. can be 
`line.forEach((item, indexX) => new BlockModel(this.ctx, item).fillBoardBlock(indexX, indexY)`

2019-11-18 13:21 UTC, oleksandrstarov commented on src/app/models/figure.model.ts
> +      matrixWithFigure[i] = lineWithFigure.slice();
why not to keep using `= [..lineWithFigere]` ?

2019-11-18 13:21 UTC, oleksandrstarov commented on src/app/models/figure.model.ts
> +  }
can be changed into, what do you think?
`showFigure(height: number, boardMatrix: FiguresColors[][]): FiguresColors[][] {
    const matrixWithFigure = [...boardMatrix];

    this.figureMatrix.forEach((line, index) => {
      const targetLine = [...boardMatrix[index + height]];
      targetLine.splice(CENTRAL_ITEM, line.length, ...line);
      matrixWithFigure[index + height] = [...targetLine];
    });
    return matrixWithFigure;
  }
`

2019-11-18 13:45 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +  private boardMatrix: any[];
Done

2019-11-18 13:54 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +  play(): void {
Done

2019-11-18 13:54 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +          block.fillBoardBlock(indexX, indexY);
Done

2019-11-18 13:55 UTC, IraCherginyshka commented on src/app/models/figure.model.ts
> +      matrixWithFigure[i] = lineWithFigure.slice();
True

2019-11-18 14:04 UTC, IraCherginyshka commented on src/app/models/figure.model.ts
> +  }
Красиво
I changed

2019-11-18 14:13 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +  makeBoardEmptyMatrix(width: number, height: number): FiguresColors[][] {
Done

2019-11-18 17:39 UTC, oleksandrstarov approved these changes

2019-11-18 17:39 UTC, merged