Feature/ATG-62 Random figures
IraCherginyshka/AwesomeTetrisGame pull request #23
Opened 2019-11-19 09:45 UTC by IraCherginyshka

Random figures with color enum

2019-11-19 10:20 UTC, oleksandrstarov requested changes

2019-11-19 10:20 UTC, oleksandrstarov commented on src/app/models/figure.model.ts
> +  public figureMatrix = FiguresMatrixConst[Math.floor(Math.random() * FiguresMatrixConst.length)];
I would put this into private function - getRandomFigure(); and put call into constructor

2019-11-19 16:14 UTC, IraCherginyshka commented on src/app/models/figure.model.ts
> +  public figureMatrix = FiguresMatrixConst[Math.floor(Math.random() * FiguresMatrixConst.length)];
Done!

2019-11-20 09:29 UTC, oleksandrstarov approved these changes

2019-11-20 09:31 UTC, merged