Feature/ATG-68 Service for game state
IraCherginyshka/AwesomeTetrisGame pull request #25
Opened 2019-11-20 13:32 UTC by IraCherginyshka

Create game-state service for whole project
Management information about state of game
Pause/Reset buttons
Change folders for controls

2019-11-20 16:24 UTC, oleksandrstarov requested changes

2019-11-20 16:24 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +    this.boardMatrix = MatrixModel.makeBoardEmptyMatrix(
Not sure that Matrix model should contain logic for empty matrix generation, i think it was more appropriate place before

2019-11-20 16:24 UTC, oleksandrstarov commented on src/app/components/game-state-controls/game-state-controls.component.html
> +  <button class="controls-action reset" (click)="resetGame()">
these functions are private thus are not accessible from template , it wont build in production mode

2019-11-20 16:24 UTC, oleksandrstarov commented on src/app/components/game-state-controls/game-state-controls.component.ts
> +  }
as a rule we are not creating unused functions

2019-11-20 16:24 UTC, oleksandrstarov commented on src/app/components/game-state-controls/game-state-controls.component.ts
> +  selector: 'atg-game-controls',
Some mess with selectors here

2019-11-20 16:24 UTC, oleksandrstarov commented on src/app/components/game-controls/game-controls.component.ts
> +  selector: 'atg-game-state-controls',
Please align selector with class name

2019-11-20 16:24 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +    const newMatrix = new MatrixModel(this.ctx);
I would not create MatrixModel, as it actually not a model but just separate object with one dependency and static function. For me it more obvious to have draw function in this class or in a service

2019-11-20 16:24 UTC, oleksandrstarov commented on src/app/components/game-state-controls/game-state-controls.component.html
> +  <button class="controls-action pause" (click)="pauseGame()">
Same as above

2019-11-20 16:24 UTC, oleksandrstarov commented on src/app/components/game-state-controls/game-state-controls.component.spec.ts
> +describe('GameControlsComponent', () => {
We have one component as import but another one as test name? Looks like a mistake, please check this

2019-11-21 08:32 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +    this.boardMatrix = MatrixModel.makeBoardEmptyMatrix(
Ok

2019-11-21 08:34 UTC, IraCherginyshka commented on src/app/components/game-state-controls/game-state-controls.component.html
> +  <button class="controls-action reset" (click)="resetGame()">
Changed

2019-11-21 08:34 UTC, IraCherginyshka commented on src/app/components/game-state-controls/game-state-controls.component.ts
> +  }
Deleted

2019-11-21 08:36 UTC, IraCherginyshka commented on src/app/components/game-state-controls/game-state-controls.component.ts
> +  selector: 'atg-game-controls',
Fixed

2019-11-21 08:36 UTC, IraCherginyshka commented on src/app/components/game-controls/game-controls.component.ts
> +  selector: 'atg-game-state-controls',
Fixed

2019-11-21 08:37 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +    const newMatrix = new MatrixModel(this.ctx);
Ok

2019-11-21 08:39 UTC, IraCherginyshka commented on src/app/components/game-state-controls/game-state-controls.component.html
> +  <button class="controls-action pause" (click)="pauseGame()">
Done

2019-11-21 08:40 UTC, IraCherginyshka commented on src/app/components/game-state-controls/game-state-controls.component.spec.ts
> +describe('GameControlsComponent', () => {
Fixed

2019-11-21 12:09 UTC, oleksandrstarov requested changes

2019-11-21 12:09 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +    return matrix.forEach((line, indexY) => {
so this is void function or it returns FiguresColors[][] ?

2019-11-21 12:09 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +  }
Please separate functions by empty line

2019-11-21 13:44 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +  }
Ok

2019-11-21 13:44 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +    return matrix.forEach((line, indexY) => {
Fixed

2019-11-21 13:54 UTC, oleksandrstarov approved these changes

2019-11-21 13:54 UTC, merged