Feature/ATG-69 Keyboard event (left, right)
IraCherginyshka/AwesomeTetrisGame pull request #26
Opened 2019-11-20 15:24 UTC by IraCherginyshka

Create GameMovementService
Add HostListener to controls component
Create enum with figures-movement

2019-11-20 16:57 UTC, oleksandrstarov requested changes

2019-11-20 16:57 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +        }
I would introduce local variable - nextPosition = this.figurePosition + gameMove
and then check if this is allowed.
So this could look like
`.getMoveStep()

      .pipe(

           map(value => value + this.figurePosition)

            filter((nextPosition) => nextPosition >= 0 && next position <= QUANTITY_BLOCKS_WIDTH)

        )

      .subscribe((nextPosition) => this.figurePosition = nextPosition)`

2019-11-20 16:57 UTC, oleksandrstarov commented on src/app/services/game-movement.service.ts
> +  public getMoveStep(): Observable<> {
Lets rename to onNextStep  - as this will return a subscription

2019-11-21 08:47 UTC, IraCherginyshka commented on src/app/services/game-movement.service.ts
> +  public getMoveStep(): Observable<> {
Done

2019-11-21 09:34 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +        }
Done

2019-11-21 13:29 UTC, oleksandrstarov requested changes

2019-11-21 13:29 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +      });
Please, do not use {} - this can be written inline

2019-11-21 13:53 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +      });
I can't 
The ESLint : Arrow function should not return assignment.(no-return-assign)
Should I change rules?

2019-11-21 13:57 UTC, oleksandrstarov approved these changes

2019-11-21 16:56 UTC, oleksandrstarov approved these changes

2019-11-21 16:56 UTC, merged