Feature/ATG-33 Next figure
IraCherginyshka/AwesomeTetrisGame pull request #33
Opened 2019-11-27 16:52 UTC by IraCherginyshka

create board model
update gameService
logic nextFigure component

2019-11-28 14:40 UTC, oleksandrstarov requested changes

2019-11-28 14:40 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +    this.currentFigure = this.gameService.currentFigure;
it is better practice to use function to some property from service and make property private

2019-11-28 14:40 UTC, oleksandrstarov commented on src/app/components/game-next-figure/game-next-figure.component.ts
> +    this.subscriptionNext = this.gameService.onUpdateFigures().subscribe(() => {
.onUpdateFigures() is not the best naming >> onNewFigureCreated()
and it is better to pass figure matrix via .next() so we catch this in subscription

2019-11-28 14:40 UTC, oleksandrstarov commented on src/app/models/block.model.ts
> +  fillBoardBlock(x: number, y: number, nextFigure: boolean): void {
nextFigure naming should be isNextFigure for boolean

2019-11-28 14:40 UTC, oleksandrstarov commented on src/app/models/block.model.ts
> +    }
maybe 
 if (!nextFigure || (nextFigure && this.ctx.fillStyle !== FiguresColors.DEFAULT)) {
?

2019-11-28 14:40 UTC, oleksandrstarov commented on src/app/models/block.model.ts
> +  fillBoardBlock(x: number, y: number, nextFigure: boolean): void {
Should be public?

2019-11-28 14:40 UTC, oleksandrstarov commented on src/app/models/block.model.ts
>    constructor(private ctx: CanvasRenderingContext2D, color: string) {
Well, lets try to use Abstract class with default fillBoardBlock function and separate fill stroke one for GameBlockModel and other for NextBlockModel, what do you think, Iryna?

2019-11-28 14:40 UTC, oleksandrstarov commented on src/app/models/board.model.ts
> +        new BlockModel(this.ctx, item).fillBoardBlock(indexX, indexY, nextFigure),
With classes for Blocks we can only pass isNextFigure to this function and create appropriate model in loop

2019-11-28 14:40 UTC, oleksandrstarov commented on src/app/models/board.model.ts
> +  public drawBoard(matrix: FiguresColors[][], nextFigure: boolean): void {
nextFigure >> isNextFigure

2019-11-28 14:40 UTC, oleksandrstarov commented on src/app/services/game.service.ts
> +  private nextFigureSubject = new Subject<void>();
Lets use FigureModel instead of void

2019-11-28 15:28 UTC, IraCherginyshka commented on src/app/services/game.service.ts
> +  private nextFigureSubject = new Subject<void>();
Done

2019-11-28 15:29 UTC, IraCherginyshka commented on src/app/models/board.model.ts
> +  public drawBoard(matrix: FiguresColors[][], nextFigure: boolean): void {
Done

2019-11-28 15:46 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +    this.currentFigure = this.gameService.currentFigure;
Done

2019-11-28 15:48 UTC, IraCherginyshka commented on src/app/components/game-next-figure/game-next-figure.component.ts
> +    this.subscriptionNext = this.gameService.onUpdateFigures().subscribe(() => {
Done

2019-11-28 15:49 UTC, IraCherginyshka commented on src/app/models/block.model.ts
> +  fillBoardBlock(x: number, y: number, nextFigure: boolean): void {
Changed

2019-11-28 15:50 UTC, IraCherginyshka commented on src/app/models/block.model.ts
> +    }
Yes. Changed

2019-11-28 15:51 UTC, IraCherginyshka commented on src/app/models/block.model.ts
> +  fillBoardBlock(x: number, y: number, nextFigure: boolean): void {
No
Changed

2019-11-28 15:51 UTC, IraCherginyshka commented on src/app/models/board.model.ts
> +        new BlockModel(this.ctx, item).fillBoardBlock(indexX, indexY, nextFigure),
Fixed

2019-11-29 10:57 UTC, IraCherginyshka commented on src/app/models/block.model.ts
>    constructor(private ctx: CanvasRenderingContext2D, color: string) {
Changed
I hope

2019-11-29 12:47 UTC, oleksandrstarov requested changes

2019-11-29 12:47 UTC, oleksandrstarov commented on src/app/models/block.model.ts
>    fillBoardBlock(x: number, y: number): void {
We can keep implementation in abstract class and create additional abstract fillStroke function which will be implemented in child classes

2019-11-29 15:16 UTC, oleksandrstarov approved these changes

2019-11-29 15:16 UTC, merged