Feature/ATG-64 Update board. Checking collision detection.
IraCherginyshka/AwesomeTetrisGame pull request #34
Opened 2019-11-29 11:48 UTC by IraCherginyshka

2019-11-29 14:41 UTC, oleksandrstarov requested changes

2019-11-29 14:41 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +    figure.forEach((line, indexY) => {
can we refactor to use Array.every function?

2019-11-29 14:41 UTC, oleksandrstarov commented on src/app/models/figure.model.ts
> +          activePosition = ind;
what does ind means?

2019-11-29 15:00 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +    figure.forEach((line, indexY) => {
Yes
Changed

2019-11-29 15:18 UTC, IraCherginyshka commented on src/app/models/figure.model.ts
> +          activePosition = ind;
I changed name

2019-12-02 12:32 UTC, oleksandrstarov requested changes

2019-12-02 12:32 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +        return true;
can we avoid code foldings of if by using such approach

`if (block === FiguresColors.DEFAULT) {
         return true;
}
const x = this.figurePosition + indexX + step;
const y = this.lineWithFigure + indexY;
if (x >= 0 && x <= QUANTITY_BLOCKS_WIDTH && y < QUANTITY_BLOCKS_HEIGHT) {
           return this.boardMatrix[y][x] === FiguresColors.DEFAULT;
 }
 return false;
`

2019-12-02 13:29 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +        return true;
Changed

2019-12-02 17:35 UTC, oleksandrstarov approved these changes

2019-12-02 17:35 UTC, merged