Feature/ATG-37  Delete filled line
IraCherginyshka/AwesomeTetrisGame pull request #36
Opened 2019-12-03 10:46 UTC by IraCherginyshka

2019-12-03 11:57 UTC, oleksandrstarov requested changes

2019-12-03 11:57 UTC, oleksandrstarov commented on src/app/models/board.model.ts
> +  static findFilledLine(
Please refactor into
public static findFilledLine(....): number[] { return figure.filter((line, index) => board[lineIndex - 1 + index].every((block) => block !== FiguresColors.DEFAULT )) }

2019-12-04 08:27 UTC, IraCherginyshka commented on src/app/models/board.model.ts
> +  static findFilledLine(
Fixed

2019-12-04 11:29 UTC, oleksandrstarov approved these changes

2019-12-04 11:29 UTC, merged