Feature/ATG-66 Display LOST game
IraCherginyshka/AwesomeTetrisGame pull request #38
Opened 2019-12-03 16:32 UTC by IraCherginyshka

Create lostGameSubject
isLostGame condition

2019-12-03 20:28 UTC, oleksandrstarov requested changes

2019-12-03 20:28 UTC, oleksandrstarov commented on src/app/components/game-controls/game-controls.component.ts
> +    this.subscriptionLost = this.gameService.onLostGame().subscribe((value) => {
value is never used...

2019-12-03 20:28 UTC, oleksandrstarov commented on src/app/components/game-state-controls/game-state-controls.component.ts
> +    this.subscriptionLost = this.gameService.onLostGame().subscribe((value) => {
value is never used

2019-12-03 20:28 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +    this.isPlaying = false;
this looks like data duplication since we have service to hold and share these values - i would recommend to use it - so set from here and add a subscribtion to track these changes

2019-12-03 20:28 UTC, oleksandrstarov commented on src/app/components/game-state-controls/game-state-controls.component.ts
> +      this.isLostGame = false;
looks strange and I might miss something but is this values are ever used? seems that we only set this and never read

2019-12-04 07:55 UTC, IraCherginyshka commented on src/app/components/game-controls/game-controls.component.ts
> +    this.subscriptionLost = this.gameService.onLostGame().subscribe((value) => {
Yes
There is no value

2019-12-04 07:55 UTC, IraCherginyshka commented on src/app/components/game-state-controls/game-state-controls.component.ts
> +    this.subscriptionLost = this.gameService.onLostGame().subscribe((value) => {
Fixed

2019-12-04 11:17 UTC, oleksandrstarov requested changes

2019-12-04 11:17 UTC, oleksandrstarov commented on src/app/components/game-state-controls/game-state-controls.component.ts
> +      this.isLostGame = false;
Still valid...

2019-12-04 11:17 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +      this.textStateOverlay = 'pause';
Please update and use GameState enum instead of string literals

2019-12-04 11:22 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +      this.textStateOverlay = 'pause';
Done

2019-12-04 11:40 UTC, IraCherginyshka commented on src/app/components/game-state-controls/game-state-controls.component.ts
> +      this.isLostGame = false;
Deleted

2019-12-04 14:17 UTC, oleksandrstarov approved these changes

2019-12-04 14:19 UTC, merged