Feature/ATG-34 Increase Level
IraCherginyshka/AwesomeTetrisGame pull request #46
Opened 2019-12-10 13:41 UTC by IraCherginyshka

Update information about current level => increase speed]

Improve Reset game

Use async pipes in information component

2019-12-10 14:10 UTC, oleksandrstarov requested changes

2019-12-10 14:10 UTC, oleksandrstarov commented on src/app/components/game-information/game-information.component.ts
> +  private observableLines$: Observable<{
private should not be used on templates

2019-12-10 14:10 UTC, oleksandrstarov commented on src/app/services/game.service.ts
>    private numberLinesSubject = new Subject<{
I think we should Use BehaviourSubject for this case

2019-12-10 14:10 UTC, oleksandrstarov commented on src/app/components/game-information/game-information.component.ts
> +    this.observableLines$ = this.gameService.onUpdateGameInformation();
please move the subscription to the constructor to avoid undefined, and use BehaviourSubject to get initial values on subscribe

2019-12-10 14:10 UTC, oleksandrstarov commented on src/app/services/game.service.ts
> +    level: number;
this type is quite common across the files - please extract it to the global type or create interface

2019-12-10 14:10 UTC, oleksandrstarov commented on src/app/components/game-information/game-information.component.ts
> +  private observableLines$: Observable<{
also the namings is strange... look like gameStats$ is better, no need to explicitly set type in name observableBlaBlaBla - the dollar sign shows that this is fancy observable

2019-12-10 14:14 UTC, IraCherginyshka commented on src/app/components/game-information/game-information.component.ts
> +  private observableLines$: Observable<{
Done

2019-12-10 14:16 UTC, IraCherginyshka commented on src/app/components/game-information/game-information.component.ts
> +  private observableLines$: Observable<{
Ok
I changed

2019-12-10 15:54 UTC, IraCherginyshka commented on src/app/components/game-information/game-information.component.ts
> +    this.observableLines$ = this.gameService.onUpdateGameInformation();
Ok
I moved

2019-12-10 16:28 UTC, oleksandrstarov requested changes

2019-12-10 16:28 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +      if (this.currentLevel !== level) {
please move this condition to the pipe- filter operator for better readability

2019-12-10 16:46 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +      if (this.currentLevel !== level) {
Done

2019-12-10 17:01 UTC, IraCherginyshka commented on src/app/services/game.service.ts
>    private numberLinesSubject = new Subject<{
Changed

2019-12-10 17:02 UTC, IraCherginyshka commented on src/app/services/game.service.ts
> +    level: number;
I created Interface

2019-12-11 10:31 UTC, oleksandrstarov approved these changes
Looks Awesome!

2019-12-11 10:31 UTC, merged