Code review
IraCherginyshka/AwesomeTetrisGame pull request #55
Opened 2019-12-31 09:43 UTC by IraCherginyshka

2020-01-06 14:50 UTC, oleksandrstarov requested changes

2020-01-06 14:50 UTC, oleksandrstarov commented on server/app.js
> +  const user = new User(req.body);
no variable is required

2020-01-06 14:50 UTC, oleksandrstarov commented on server/app.js
> +    });
should be moved to db.js, db.createUser(req.body).then().catch()

2020-01-06 14:50 UTC, oleksandrstarov commented on src/app/app.module.ts
> +import { ToastContainerModule, ToastrModule } from 'ngx-toastr';
move one line up

2020-01-06 14:50 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.scss
> +  background-color: rgba($primary-color, 0.85);
add variable to .85

2020-01-06 14:50 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +    const reverseMatrix = [...figureMatrix];
[...figureMatrix].reverse();

2020-01-06 14:50 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +    this.currentMatrix = newFigure.showFigure(
newFigure >> new FigureModel()

2020-01-06 14:50 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +      if (this.checkCollisionDetection(0, this.currentFigure)) {
add const hasCollision = this.checkCollisionDetection(0, this.currentFigure);

2020-01-06 14:50 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +        this.lineWithFigure === 0
!lineWith...

2020-01-06 14:50 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +    clearInterval(this.timeInterval);
stopGame()

2020-01-06 14:50 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +    clearInterval(this.timeInterval);
stopGame()

2020-01-06 14:50 UTC, oleksandrstarov commented on src/app/components/game-controls/game-controls.component.ts
> +  private isPlaying: boolean;
separate public/private

2020-01-06 14:50 UTC, oleksandrstarov commented on src/app/components/game-header/game-header.component.html
> +      <a class="header-link" [routerLink]="['/login']">login</a>
please check routerLinkActive

2020-01-06 14:50 UTC, oleksandrstarov commented on src/app/components/game-header/game-header.component.ts
> +          this.userIsAuthenticated = false;
can be this.userIsAuthenticated = !!user

2020-01-08 17:33 UTC, IraCherginyshka commented on src/app/components/game-header/game-header.component.html
> +      <a class="header-link" [routerLink]="['/login']">login</a>
Thanks

2020-01-09 10:51 UTC, closed without merging