Feature/ATG-10 Create main field with general styles
IraCherginyshka/AwesomeTetrisGame pull request #6
Opened 2019-11-05 10:56 UTC by IraCherginyshka

Create components (Header, Board, Option, Controls, Information, Leaderboard)
Create images folder
Add icons
Add general styles

2019-11-05 14:08 UTC, oleksandrstarov requested changes

2019-11-05 14:08 UTC, oleksandrstarov commented on src/app/app.component.scss
> +  max-width: 1100px; //var
Please update using available variables (already merged)

2019-11-05 14:08 UTC, oleksandrstarov commented on src/app/app.component.scss
> +  //font-size: ; //var
Just a question - we set font-size as some pixels value on top element (html/body) and rem are related to default font size value. Is this set?

2019-11-05 14:08 UTC, oleksandrstarov commented on src/app/components/game-control-option/game-control-option.component.html
> +
Remove extra line

2019-11-05 14:08 UTC, oleksandrstarov commented on src/app/components/game-control-option/game-control-option.component.html
> +
I recommend to set up rules by using https://eslint.org/docs/rules/ or ready-to-use plugin

2019-11-05 14:08 UTC, oleksandrstarov commented on src/app/components/game-control-option/game-control-option.component.ts
> +  // constructor() { }
As a rule we should not comment any code in merge requests

2019-11-05 14:08 UTC, oleksandrstarov commented on src/app/components/game-controls/game-controls.component.ts
> +  // constructor() { }
Same as above

2019-11-05 14:08 UTC, oleksandrstarov commented on src/app/components/game-header/game-header.component.ts
> +  // constructor() { }
Comment

2019-11-05 14:08 UTC, oleksandrstarov commented on src/app/components/game-information/game-information.component.ts
> +  // constructor() { }
Comment

2019-11-05 14:08 UTC, oleksandrstarov commented on src/app/components/game-leaderboard/game-leaderboard.component.ts
> +  // constructor() { }
Comment

2019-11-05 14:08 UTC, oleksandrstarov commented on src/app/components/game-loader/game-loader.component.ts
> +  // constructor() { }
Comment

2019-11-05 14:08 UTC, oleksandrstarov commented on src/styles.scss
> +
I recommend to set up eslint rules and create pre-push hook to run es lint over all files and check for errors. If any - prevent commit, check https://www.npmjs.com/package/husky

2019-11-05 14:17 UTC, IraCherginyshka commented on src/app/app.component.scss
> +  max-width: 1100px; //var
Done

2019-11-05 14:17 UTC, IraCherginyshka commented on src/app/app.component.scss
> +  //font-size: ; //var
Not set.
I set font-size to html.
Done

2019-11-05 14:21 UTC, IraCherginyshka commented on src/app/components/game-control-option/game-control-option.component.html
> +
Done

2019-11-05 14:26 UTC, IraCherginyshka commented on src/app/components/game-control-option/game-control-option.component.ts
> +  // constructor() { }
I used comment, because EsLint throw Error (useless constructor)
Must I delete constructor from every component?

2019-11-05 17:14 UTC, IraCherginyshka commented on src/app/components/game-control-option/game-control-option.component.ts
> +  // constructor() { }
Done

2019-11-05 17:14 UTC, IraCherginyshka commented on src/app/components/game-controls/game-controls.component.ts
> +  // constructor() { }
Done

2019-11-05 17:14 UTC, IraCherginyshka commented on src/app/components/game-header/game-header.component.ts
> +  // constructor() { }
Done

2019-11-05 17:14 UTC, IraCherginyshka commented on src/app/components/game-information/game-information.component.ts
> +  // constructor() { }
Done

2019-11-05 17:14 UTC, IraCherginyshka commented on src/app/components/game-leaderboard/game-leaderboard.component.ts
> +  // constructor() { }
Done

2019-11-05 17:14 UTC, IraCherginyshka commented on src/app/components/game-loader/game-loader.component.ts
> +  // constructor() { }
Done

2019-11-05 17:14 UTC, IraCherginyshka commented on src/styles.scss
> +
Done

2019-11-06 09:48 UTC, oleksandrstarov approved these changes

2019-11-06 09:48 UTC, merged