Feature/ATG-15 Option component
IraCherginyshka/AwesomeTetrisGame pull request #60
Opened 2020-01-08 14:21 UTC by IraCherginyshka

save customize controls in localstorage
update logic in controls component & state-controls component

2020-01-08 15:19 UTC, oleksandrstarov requested changes

2020-01-08 15:19 UTC, oleksandrstarov commented on src/app/components/game-control-option/game-control-option.component.ts
> +      const savedControls = JSON.parse(localStorage.getItem('controls'));
I suggest to use const savedControls = JSON.parse(localStorage.getItem('controls'));

if (savedControls) ...
else ...

2020-01-08 15:19 UTC, oleksandrstarov commented on src/app/components/game-controls/game-controls.component.ts
> +    } else {
Same as previous comment

2020-01-08 15:19 UTC, oleksandrstarov commented on src/app/components/game-state-controls/game-state-controls.component.ts
> +    } else {
Same as above

2020-01-08 15:19 UTC, oleksandrstarov commented on src/app/interfaces/controlsState.interface.ts
> +  right?: string | DefaultSettings;
Not sure why do we need to use optional fields? cant find any particular place. If there requirements for this in single place - we can use Partial<ControlsStateObject> https://www.typescriptlang.org/docs/handbook/utility-types.html#partialt

2020-01-09 11:34 UTC, IraCherginyshka commented on src/app/components/game-control-option/game-control-option.component.ts
> +      const savedControls = JSON.parse(localStorage.getItem('controls'));
Changed

2020-01-09 11:39 UTC, IraCherginyshka commented on src/app/components/game-controls/game-controls.component.ts
> +    } else {
Changed

2020-01-09 11:40 UTC, IraCherginyshka commented on src/app/components/game-state-controls/game-state-controls.component.ts
> +    } else {
Changed

2020-01-09 11:49 UTC, IraCherginyshka commented on src/app/interfaces/controlsState.interface.ts
> +  right?: string | DefaultSettings;
Done

2020-01-09 12:30 UTC, oleksandrstarov approved these changes

2020-01-09 12:30 UTC, merged