Feature/ATG-106 Unit test
IraCherginyshka/AwesomeTetrisGame pull request #69
Opened 2020-01-14 11:10 UTC by IraCherginyshka

2020-01-21 20:22 UTC, oleksandrstarov requested changes

2020-01-21 20:22 UTC, oleksandrstarov commented on .github/workflows/build-app.yml
> +        npm run eslint
the | symbol is in use for multiple commands and we have a single execution here, please, remove the | and write script at the same line (as it done on line 33 for example)

2020-01-21 20:22 UTC, oleksandrstarov commented on .github/workflows/build-app.yml
> +        npm run test
same as above

2020-01-21 20:22 UTC, oleksandrstarov commented on .github/workflows/build-app.yml
> +    - name: linter
Please note that on Git side we do not have any node_modules yet, the next steps will fail due to absence of linter and test packages, we have to first install npm packages and only after that we can run linter and tests

2020-01-21 20:22 UTC, oleksandrstarov commented on README.md
> +- run "ng build --prod",
Please update this file according to the changes in pipeline (lint and test steps)

2020-01-21 20:22 UTC, oleksandrstarov commented on README.md
> +- delete all unnecessary files and directories
I would write delete all source files and folders that are not required for deployment

2020-01-21 20:22 UTC, oleksandrstarov commented on package.json
> +    "ngx-mock-provider": "^1.0.6",
Please move this package to dev dependencies, as this is obviously not required for build, same for "eslint-config-prettier"

2020-01-21 20:22 UTC, oleksandrstarov commented on src/app/app.component.spec.ts
> +        ToastContainerDirective,
I know this is done only to pass the testing build, but please rewrite this to use mocks instead of real components

2020-01-21 20:22 UTC, oleksandrstarov commented on src/app/components/game-control-option/game-control-option.component.spec.ts
> +    button.click();
This looks good, but it is enough to manually call component.saveControls() and observe the results

2020-01-21 20:22 UTC, oleksandrstarov commented on src/app/components/game-header/game-header.component.spec.ts
> +      declarations: [GameHeaderComponent, PlayerProfileHeaderComponent, ToastContainerDirective],
Same for component declarations - please use Mocks

2020-01-21 20:22 UTC, oleksandrstarov commented on src/app/components/game-leaderboard/game-leaderboard.component.html
> +        <span class="leaderboard_index">{{ currentPlayerPlace + 1 }}</span>
I would rename variable to currentPlayerIndex to avoid confusion

2020-01-21 20:22 UTC, oleksandrstarov commented on src/app/components/game-leaderboard/game-leaderboard.component.ts
> +          (player) => player.username === this.currentPlayerName,
can be shortened to ({ username }) => username === this.currentPlayerName,

2020-01-21 20:22 UTC, oleksandrstarov commented on src/app/components/game-login-form/game-login-form.component.spec.ts
> +import { RouterModule } from '@angular/router';
Not sure we need to have this module since we have RouterTestingModule

2020-01-21 20:22 UTC, oleksandrstarov commented on src/app/components/game-main/game-main.component.spec.ts
> +        GameControlsComponent,
Please mock these components

2020-01-22 10:19 UTC, IraCherginyshka commented on package.json
> +    "ngx-mock-provider": "^1.0.6",
In the beginning, I added this package to dev dependencies and got the error
ESLint: 'ngx-mock-provider' should be listed in the project's dependencies, not devDependencies.(import/no-extraneous-dependencies)
What should I do?

"eslint-config-prettier" I moved.

2020-01-22 10:39 UTC, IraCherginyshka commented on package.json
> +    "ngx-mock-provider": "^1.0.6",
I got the same error about ng2-mock-component: 
ESLint: 'ng2-mock-component' should be listed in the project's dependencies, not devDependencies.(import/no-extraneous-dependencies)

2020-01-22 11:52 UTC, IraCherginyshka commented on src/app/app.component.spec.ts
> +        ToastContainerDirective,
Done

2020-01-22 11:52 UTC, IraCherginyshka commented on src/app/components/game-header/game-header.component.spec.ts
> +      declarations: [GameHeaderComponent, PlayerProfileHeaderComponent, ToastContainerDirective],
Done

2020-01-22 11:52 UTC, IraCherginyshka commented on src/app/components/game-login-form/game-login-form.component.spec.ts
> +import { RouterModule } from '@angular/router';
Deleted

2020-01-22 11:53 UTC, IraCherginyshka commented on src/app/components/game-main/game-main.component.spec.ts
> +        GameControlsComponent,
Done

2020-01-22 11:54 UTC, IraCherginyshka commented on src/app/components/game-leaderboard/game-leaderboard.component.ts
> +          (player) => player.username === this.currentPlayerName,
Changed

2020-01-22 11:56 UTC, IraCherginyshka commented on src/app/components/game-leaderboard/game-leaderboard.component.html
> +        <span class="leaderboard_index">{{ currentPlayerPlace + 1 }}</span>
Renamed

2020-01-22 11:57 UTC, IraCherginyshka commented on README.md
> +- delete all unnecessary files and directories
Changed

2020-01-22 12:02 UTC, IraCherginyshka commented on .github/workflows/build-app.yml
> +        npm run eslint
Deleted

2020-01-22 12:52 UTC, IraCherginyshka commented on .github/workflows/build-app.yml
> +    - name: linter
Fixed

2020-01-22 12:53 UTC, IraCherginyshka commented on .github/workflows/build-app.yml
> +        npm run test
Deleted

2020-01-22 12:55 UTC, IraCherginyshka commented on README.md
> +- run "ng build --prod",
Done

2020-01-22 13:17 UTC, IraCherginyshka commented on src/app/components/game-control-option/game-control-option.component.spec.ts
> +    button.click();
Done

2020-01-22 14:55 UTC, merged