bugfix/ATG-333 BugFix
IraCherginyshka/AwesomeTetrisGame pull request #70
Opened 2020-01-21 10:01 UTC by IraCherginyshka

fix uppercase & lowercase for input custom controls

2020-01-21 19:45 UTC, oleksandrstarov requested changes

2020-01-21 19:45 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +          this.gameInformation = gameStats;
Can be inline

2020-01-21 19:45 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +      .pipe(filter((logout) => logout === 'logout'))
I would call variable action instead of logout, so we get action => action === 'logout'

2020-01-21 19:45 UTC, oleksandrstarov commented on src/app/components/game-login-form/game-login-form.component.html
> +            <label for="flying" class="login__label">
no need to keep for attribute since we refactor img to be inside label

2020-01-21 19:45 UTC, oleksandrstarov commented on src/app/services/game.service.ts
> +  public getPlayerGameResult(): Observable<GameResult[]> {
I noticed that public access modifier is not used for functions everywhere in the code, please review and align approach across files to be the same.

2020-01-21 19:45 UTC, oleksandrstarov commented on src/app/services/user.service.ts
> +    this.authListener.next('logout');
This solution is not the most elegant I've seen. At least introduce a new Enum with this value as it in use in different places (service and component)

2020-01-22 09:19 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +          this.gameInformation = gameStats;
I get the error: 
ESLint: Arrow function should not return assignment.(no-return-assign)

2020-01-22 09:20 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +      .pipe(filter((logout) => logout === 'logout'))
Changed

2020-01-22 09:23 UTC, IraCherginyshka commented on src/app/components/game-login-form/game-login-form.component.html
> +            <label for="flying" class="login__label">
It is a label for outside input

2020-01-22 09:31 UTC, IraCherginyshka commented on src/app/services/game.service.ts
> +  public getPlayerGameResult(): Observable<GameResult[]> {
Done

2020-01-22 09:35 UTC, IraCherginyshka commented on src/app/services/user.service.ts
> +    this.authListener.next('logout');
I also don't like this solution, but I didn't find a better one.
If you have a good idea, please, tell me.

2020-01-22 15:29 UTC, oleksandrstarov approved these changes

2020-01-22 15:29 UTC, merged