Feature/ATG-121 Socket.io
IraCherginyshka/AwesomeTetrisGame pull request #76
Opened 2020-01-29 17:58 UTC by IraCherginyshka

2020-02-03 12:32 UTC, oleksandrstarov requested changes

2020-02-03 12:32 UTC, oleksandrstarov commented on package.json
> +    "@types/socket.io-client": "^1.4.32",
Please - move types to dev dependencies

2020-02-03 12:32 UTC, oleksandrstarov commented on package.json
> +    "ngx-mock-provider": "^1.0.6",
Please move test dependencies into dev dependencies

2020-02-03 12:32 UTC, oleksandrstarov commented on server/socketServer.js
> +let server = http.Server(app);
should be const, also I believe we should use only one server instance, same as in server.js and here we set second server instead

2020-02-03 12:32 UTC, oleksandrstarov commented on server/socketServer.js
> +let io = socketIO(server);
should be const

2020-02-03 12:32 UTC, oleksandrstarov commented on server/server.js
> +const socketServer = require('./socketServer');
this is never user

2020-02-03 12:32 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +            }
is this code same for all steps? if so - can we move this to the end, so no duplicated code is used

2020-02-03 12:32 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +          }
We can set auth check within sendStats.. function - this will reduce a lot of code lines

2020-02-03 12:32 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +    this.sendStatsToSocket();
why dont we have an auth check here?

2020-02-03 12:32 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +        }
Can we move socket send out of conditions? I believe we need to send update on every interval. Am I wrong?

2020-02-03 12:32 UTC, oleksandrstarov commented on src/app/components/game-information/game-information.component.ts
> +      });
why dont just use  set instead of arrays?

2020-02-03 12:32 UTC, oleksandrstarov commented on src/app/components/game-other-player/game-other-player.component.html
> +      <div *ngIf="gameStatus !== 'play'" class="overlay">{{ gameStatus }}</div>
Please use GameState enum

2020-02-03 12:32 UTC, oleksandrstarov commented on src/app/services/socket.service.ts
> +import * as io from 'socket.io-client';
We do have a @types library but no socket-io.client

2020-02-03 12:32 UTC, oleksandrstarov commented on package.json
> +    "socket.io": "^2.3.0",
this should be in server dependencies

2020-02-03 12:32 UTC, oleksandrstarov commented on src/app/services/socket.service.ts
> +  public allActiveGames(): void {
Please rename this funtion to be verb

2020-02-03 13:28 UTC, IraCherginyshka commented on package.json
> +    "@types/socket.io-client": "^1.4.32",
Done

2020-02-03 13:29 UTC, IraCherginyshka commented on package.json
> +    "ngx-mock-provider": "^1.0.6",
Done

2020-02-03 13:34 UTC, IraCherginyshka commented on src/app/services/socket.service.ts
> +  public allActiveGames(): void {
Done

2020-02-03 13:35 UTC, IraCherginyshka commented on package.json
> +    "socket.io": "^2.3.0",
Done

2020-02-03 13:46 UTC, IraCherginyshka commented on package.json
> +    "ngx-mock-provider": "^1.0.6",
I added *spec.ts to .eslintignore

2020-02-03 13:47 UTC, IraCherginyshka commented on src/app/services/socket.service.ts
> +import * as io from 'socket.io-client';
Installed socket.io-client

2020-02-03 13:51 UTC, IraCherginyshka commented on src/app/components/game-other-player/game-other-player.component.html
> +      <div *ngIf="gameStatus !== 'play'" class="overlay">{{ gameStatus }}</div>
Done

2020-02-03 14:27 UTC, IraCherginyshka commented on src/app/components/game-information/game-information.component.ts
> +      });
Changed

2020-02-03 15:11 UTC, IraCherginyshka commented on server/socketServer.js
> +let server = http.Server(app);
I hope I understand you correctly

2020-02-03 15:11 UTC, IraCherginyshka commented on server/socketServer.js
> +let server = http.Server(app);
I fixed

2020-02-03 15:12 UTC, IraCherginyshka commented on server/socketServer.js
> +let io = socketIO(server);
Done

2020-02-03 15:12 UTC, IraCherginyshka commented on server/server.js
> +const socketServer = require('./socketServer');
Fixed

2020-02-03 18:56 UTC, oleksandrstarov requested changes
Please check the comments, one comment is still unprocessed from previous review

2020-02-03 18:56 UTC, oleksandrstarov commented on src/app/components/game-other-player/game-other-player.component.html
> +          src="../../../assets/images/{{ player?.avatar }}"
no need to protect player with ? as we do check this code with ngIf

2020-02-03 18:56 UTC, oleksandrstarov commented on src/app/components/game-other-player/game-other-player.component.html
> +        <section class="profile__information">
I would set ngIf player here to avoid situations when it will show an empty section with content " years, "

2020-02-04 07:45 UTC, IraCherginyshka commented on src/app/components/game-other-player/game-other-player.component.html
> +          src="../../../assets/images/{{ player?.avatar }}"
Ok. Deleted

2020-02-04 07:51 UTC, IraCherginyshka commented on src/app/components/game-other-player/game-other-player.component.html
> +        <section class="profile__information">
I set ngIf on the entire player info block. Thanks

2020-02-04 08:47 UTC, oleksandrstarov approved these changes

2020-02-04 08:47 UTC, merged