Feature/ATG-124 Responsive design
IraCherginyshka/AwesomeTetrisGame pull request #77
Opened 2020-02-05 08:37 UTC by IraCherginyshka

2020-02-05 11:05 UTC, oleksandrstarov requested changes

2020-02-05 11:05 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +    this.redrawBoard();
According to the code redraw function is going to be called on every resize event - probably we need to redraw only in case we change block size?

2020-02-05 11:05 UTC, oleksandrstarov commented on src/app/components/game-board/game-board.component.ts
> +    this.canvas.nativeElement.height = QUANTITY_BLOCKS_HEIGHT * this.blockSize;
Code duplication detected, please extract this code into a function

2020-02-05 11:05 UTC, oleksandrstarov commented on src/app/components/game-information/game-information.component.scss
> +  .mobile-display-none {
I've seen this style before - this is a good idea to extract selector to the global level. What do you think?

2020-02-05 11:05 UTC, oleksandrstarov commented on src/app/components/game-login-form/game-login-form.component.html
> +              Password*
Why do we need to have a brek here? Can we use css word-wrap instead?

2020-02-05 11:05 UTC, oleksandrstarov commented on src/app/components/game-other-player/game-other-player.component.ts
> +  }
I've seen this code before. From my poin of view it is more obvious to create separate service which will watch resize and provide block size value as observable instead of create multiple listeners...

2020-02-05 11:05 UTC, oleksandrstarov commented on src/app/components/game-other-player/game-other-player.component.ts
> +    this.canvas.nativeElement.height = QUANTITY_BLOCKS_HEIGHT * this.blockSize;
Same as above, Iryna.

2020-02-05 11:24 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +    this.redrawBoard();
Done

2020-02-05 13:18 UTC, IraCherginyshka commented on src/app/components/game-information/game-information.component.scss
> +  .mobile-display-none {
Done

2020-02-05 13:21 UTC, IraCherginyshka commented on src/app/components/game-login-form/game-login-form.component.html
> +              Password*
Yes. Fixed

2020-02-05 17:19 UTC, IraCherginyshka commented on src/app/components/game-board/game-board.component.ts
> +    this.canvas.nativeElement.height = QUANTITY_BLOCKS_HEIGHT * this.blockSize;
Fixed

2020-02-05 17:19 UTC, IraCherginyshka commented on src/app/components/game-other-player/game-other-player.component.ts
> +  }
Fixed

2020-02-05 17:19 UTC, IraCherginyshka commented on src/app/components/game-other-player/game-other-player.component.ts
> +    this.canvas.nativeElement.height = QUANTITY_BLOCKS_HEIGHT * this.blockSize;
Yes

2020-02-05 19:45 UTC, oleksandrstarov requested changes

2020-02-05 19:45 UTC, oleksandrstarov commented on src/app/components/game-control-option/game-control-option.component.ts
> +  }
Can we use resize service here too?

2020-02-05 19:45 UTC, oleksandrstarov commented on src/app/components/game-control-option/game-control-option.component.ts
> +    }
Same as above

2020-02-06 08:10 UTC, IraCherginyshka commented on src/app/components/game-control-option/game-control-option.component.ts
> +  }
Yes. Fixed

2020-02-06 08:10 UTC, IraCherginyshka commented on src/app/components/game-control-option/game-control-option.component.ts
> +    }
Ok

2020-02-06 08:36 UTC, oleksandrstarov approved these changes

2020-02-06 08:36 UTC, merged