Bugfix/ATG-123 Long press
IraCherginyshka/AwesomeTetrisGame pull request #84
Opened 2020-02-07 17:23 UTC by IraCherginyshka

Create LongPress directive to improve the game flow

2020-02-12 11:30 UTC, oleksandrstarov requested changes

2020-02-12 11:30 UTC, oleksandrstarov commented on src/app/directives/long-press.directive.ts
> +    }
Please swap condition to be if (this.moveStep === FiguresMovement.ROTATE) {///} else  {} - such conditions is easier to read

2020-02-12 11:30 UTC, oleksandrstarov commented on src/app/directives/long-press.directive.ts
> +  onMouseDown(event: Event): void {
onMouseDown and endPress functions should be the same naming style I guess

2020-02-12 11:46 UTC, IraCherginyshka commented on src/app/directives/long-press.directive.ts
> +    }
Done

2020-02-12 11:51 UTC, IraCherginyshka commented on src/app/directives/long-press.directive.ts
> +  onMouseDown(event: Event): void {
Changed

2020-02-12 12:53 UTC, oleksandrstarov requested changes

2020-02-12 12:53 UTC, oleksandrstarov commented on src/app/directives/long-press.directive.ts
> +  onMouseDown(event: Event): void {
I am very grateful for your contribution, but please push your changes

2020-02-12 12:57 UTC, IraCherginyshka commented on src/app/directives/long-press.directive.ts
> +  onMouseDown(event: Event): void {
Sorry, I have some problems with the code. Give me 10 minutes.

2020-02-24 09:15 UTC, oleksandrstarov approved these changes

2020-02-24 09:15 UTC, merged